# Generated by Django 4.2.13 on 2025-04-04 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawlings', '0002_rename_last_updated_stock_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawlings.comment')),
            ],
        ),
    ]
