# Generated by Django 4.2.13 on 2025-04-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='last_updated',
            new_name='updated_at',
        ),
    ]
